version: '3.8'

services:
  db:
    image: postgres:15
    container_name: news-db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=news_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:

